# -*- coding: utf-8 -*-
"""Vlookup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZdN8MzJaNR4QU0aE59BaASZ1cwGSTaAY
"""



import pandas as pd
import numpy as np

initial_workbook = 'student.xlsx'
info_workbook = 'ProgramEnrollment.xlsx'
output_workbook = 'output.xlsx'

df_initial = pd.read_excel(initial_workbook)
df_info = pd.read_excel(info_workbook)

# print(df_initial.columns)
# print(df_info.columns)

df_3 = pd.merge(df_initial, df_info[['StudentNumber','ProgramCode']], on='StudentNumber', how='left')
print(df_3)


df_3 = df_3.replace(np.nan, '', regex=True)
print(df_3)
df_3.to_excel(output_workbook, index=False)